include(FetchContent)
set(QT_VERSION_MAJOR 6)
if(EXISTS "${CMAKE_SOURCE_DIR}/.tools/QXlsx/QXlsx/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_QXLSX "${CMAKE_SOURCE_DIR}/.tools/QXlsx")
endif()
if(EXISTS "${CMAKE_SOURCE_DIR}/.tools/miniz/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_MINIZ "${CMAKE_SOURCE_DIR}/.tools/miniz")
endif()
FetchContent_Declare(qxlsx GIT_REPOSITORY https://github.com/QtExcel/QXlsx.git
    GIT_TAG v1.5.1.1 GIT_SHALLOW TRUE SOURCE_SUBDIR QXlsx)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(INSTALL_PROJECT OFF CACHE BOOL "" FORCE)
FetchContent_Declare(miniz GIT_REPOSITORY https://github.com/richgel999/miniz.git
    GIT_TAG 3.1.2 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(qxlsx miniz)
target_compile_definitions(miniz PUBLIC MINIZ_NO_ZLIB_COMPATIBLE_NAMES)
set(CMAKE_CXX_STANDARD 20)

if(WIN32)
    set(MUZ_PDFIUM_FILENAME pdfium.dll)
elseif(APPLE)
    set(MUZ_PDFIUM_FILENAME libpdfium.dylib)
else()
    set(MUZ_PDFIUM_FILENAME libpdfium.so)
endif()
set(MUZ_PDFIUM_DIR "${CMAKE_SOURCE_DIR}/.tools/pdfium" CACHE PATH "Native PDFium directory")
if(NOT EXISTS "${MUZ_PDFIUM_DIR}/${MUZ_PDFIUM_FILENAME}")
    message(FATAL_ERROR "Run scripts/prepare-pdfium.py with pypdfium2==5.13.0 installed first")
endif()
configure_file("${MUZ_PDFIUM_DIR}/${MUZ_PDFIUM_FILENAME}" "${CMAKE_BINARY_DIR}/${MUZ_PDFIUM_FILENAME}" COPYONLY)
file(COPY "${MUZ_PDFIUM_DIR}/licenses" DESTINATION "${CMAKE_BINARY_DIR}/pdfium-notices")
